import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Forms & Actions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark:bg-bg-dark bg-bg-light text-text-main dark:text-text-main-dark">
        {children}
      </body>
    </html>
  );
}
